appName: java-app
appReplicas: 3
containerPort: 8080
servicePort: 8080
serviceType: ClusterIP
appImage: tsmallwood23/my-repo
appVersion: java-mysqlv1.0

registrySecret:
secretType: Opaque
secretName: java-secret
secretData: docker-hub
  db_user: dGFubmVy
  db_pwd: VGFubmVyMTIz
  db_name: bXktZGI=
  db_root_pwd: TWVsaXNzYTEyMw==
configName: java-config
configData:
  db_server: mysql-primary.exercise
  pma_port: "3306"

ingress:
  hostname: 96-126-99-79.ip.linodeusercontent.com
  path: /
  pathType: Exact