appName: java-app
appReplicas: 3
containerPort: 8080
servicePort: 8080
serviceType: ClusterIP
appImage: tsmallwood23/my-repo
appVersion: java-mysqlv1.0

registrySecret: docker-hub
secretType: Opaque
secretName: java-secret
secretData:
  DB_USER: dGFubmVy
  DB_PWD: VGFubmVyMTIz
  DB_NAME: bXktZGI=
  MYSQL_ROOT_PASSWORD: TWVsaXNzYTEyMw==
configName: java-config
configData:
  DB_SERVER: mysql-primary.exercise

ingress:
  hostname: 96-126-99-79.ip.linodeusercontent.com
  path: /
  pathType: Exact